### ISSUE TITLE
Make a discord server

### ISSUE THREAD

**Issue by ApoWillow** [ZekeSmith/Illager-Expansion-Rematch#6]
I realized you are struggling with making the mods, if you don't have ideas try making a discord server, people would love to suggest their ideas in there

**Comment by ZekeZDev** [comment]
I am currently using the Warp Modding server for this purpose it was previously the HexMC discord however I plan it to be more multipurpsose. 

Late response I know but if you want to join it can be done so here: https://discord.gg/S6uH5ykDQy
